version: '3.8'
services:
  order:
    build: 
     context: ./order
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-a:3306/order_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dvhn@2001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql-a
    networks:
      - my-network
    ports:
      - "8083:8081"
    volumes:
      - order_data:/app/data 

  product:
    build: 
     context: ./product
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-b:3306/product_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dvhn@2001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: group-1
    depends_on:
      - mysql-b
    networks:
      - my-network
    ports:
      - "8084:8082"
    volumes:
      - product_data:/app/data 
  
  mysql-a:
    image: mysql:8
    environment:
      MYSQL_DATABASE: order_db
      MYSQL_ROOT_PASSWORD: Dvhn@2001
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    ports:
      - "3307:3306"
    networks:
      - my-network
    volumes:
      - db_data_a:/var/lib/mysql
      
  mysql-b:
    image: mysql:8
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_ROOT_PASSWORD: Dvhn@2001
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    ports:
      - "3308:3306"
    networks:
      - my-network
    volumes:
      - db_data_b:/var/lib/mysql

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

networks:
  my-network:
    driver: bridge

volumes:
  db_data_a:
  db_data_b:
  order_data: 
  product_data: