apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: localhost:5000/order:latest
        ports:
        - containerPort: 8081
        volumeMounts:  # This should be here
          - name: order-data
            mountPath: /app/data
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/order_db?useSSL=false&serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Dvhn@2001
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
      volumes:
      - name: order-data
