apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: localhost:5000/product:latest
        ports:
        - containerPort: 8082
        volumeMounts:
        - name: product-data
          mountPath: /app/data
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/product_db?useSSL=false&serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Dvhn@2001
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
      volumes:
      - name: product-data
